Use impl LineraNetConfig instead of LocalNetTestingConfig on end to end tests
linera-io/linera-protocol pull request #1270
Opened 2023-11-22 15:36 UTC by andresilva91

## Motivation

We need to use `impl LineraNetConfig` everywhere as we'll have more derived types of it that need to pass the end to end tests

## Proposal

Changing specific implementations to use `impl LineraNetConfig` instead. I'm not doing all the implementations on this PR as the code won't be used, so doing it in the next one where I actually attempt to pass the end to end tests

## Test Plan

CI

2023-11-22 15:36 UTC, andresilva91 commented
Current dependencies on/for this PR:
* main
  * **PR #1231** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1231?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1255** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1255?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1270** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1270?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #1265** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1265?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1270?utm_source=stack-comment).

2023-11-22 15:36 UTC, andresilva91 commented
Current dependencies on/for this PR:
* main
  * **PR #1231** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1231?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1255** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1255?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1270** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1270?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #1265** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/1265?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/1270?utm_source=stack-comment).

2023-11-22 15:37 UTC, andresilva91 commented on linera-service/src/cli_wrappers/local_kubernetes_net.rs
> +        unimplemented!()
As stated in the Summary, will implement these in the next PR

2023-11-23 07:05 UTC, ma2bd requested changes
I scoped out `test_end_to_end_reconfiguration` on purpose so that you don't have to support reconfigurations in the first iteration of Kubernetes-based e2e tests.

2023-11-23 13:57 UTC, andresilva91 commented
Oh ok, I'll skip this for now then

2023-11-23 13:57 UTC, closed without merging