Eliminate `CustomSerialize` and subsequent changes
linera-io/linera-protocol pull request #1392
Opened 2023-12-14 15:46 UTC by MathieuDutSik

## Motivation

The CusomSerialize is a bad design. Instead, the right way is to implement Serialize for Custom types.

## Proposal

The following is done:
* Elimination of `CustomMapView` and similar.
* Elimination of `CustomSerialize`.
* Introduction of specific `Serialize` trait for `Key` in social.
* For the matching Engine, the `PriceBid/PriceAsk` are introduced. This leads to a cleaner code.

## Test Plan

Unfortunately, we could not test the `matching_engine` which is currently marked as ignore and both the new and old test cannot be tested (connection lost). Test have been added for the serialize/deserialize of the `PriceAsk/PriceBid`.

## Release Plan

If the CustomSerialize is present in the documentation, then it has to be eliminated.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

2023-12-14 16:35 UTC, afck commented on examples/social/src/lib.rs
> +        serializer.serialize_bytes(&key)
Aren't we already using BCS anyway?
So it shouldn't be necessary to explicitly use it here:
```suggestion
        data.serialize(serializer)
```

2023-12-14 16:35 UTC, afck commented on examples/social/src/lib.rs
> +                })
Couldn't this just be the body of `deserialize` itself? Then we wouldn't need a `Visitor` impl at all.

```suggestion
                let (time_bytes, author, idx_bytes) =
                    ([u8; 8], ChainId, [u8; 8])::deserialize(deserializer)?;
                Ok(Key {
                    timestamp: Timestamp::from(!u64::from_be_bytes(time_bytes)),
                    author,
                    index: !u64::from_be_bytes(idx_bytes),
                })
```

2023-12-14 16:35 UTC, afck commented on examples/matching-engine/src/lib.rs
> +    pub fn to_ask(&self) -> PriceAsk {
```suggestion

    pub fn to_ask(&self) -> PriceAsk {
```

2023-12-14 16:35 UTC, afck commented on examples/matching-engine/src/lib.rs
> +        serializer.serialize_bytes(&short_key)
```suggestion
        self.price.to_be_bytes().serialize(serializer)
```

2023-12-14 16:35 UTC, afck commented on examples/matching-engine/src/lib.rs
> +        result.map(|price| Self { price })
```suggestion
        Ok(Self { price: u64::from_be_bytes(_::deserialize(deserializer)?) })
```

2023-12-14 16:35 UTC, afck commented on examples/matching-engine/src/lib.rs
> +        serializer.serialize_bytes(&short_key)
```suggestion
        (!self.price).to_be_bytes().serialize(serializer)
```

2023-12-14 16:35 UTC, afck commented on examples/matching-engine/src/lib.rs
> +        })
```suggestion
        Ok(Self { price: !u64::from_be_bytes(_::deserialize(deserializer)?) })
```

2023-12-15 00:11 UTC, ma2bd requested changes
I agree that we could remove `CustomSerialize` but in the current state of `MapView` the solution here only applies to fixed size objects. (Otherwise, after serializing values to a BCS vector,  the BCS-encoded lengths, serialized first, will ruin ordering.)

Incidentally, for many fixed size objects such as integers, it would be slightly better to shuffle the bytes but still serialize as an integer.

Following @Twey's idea, I suspect a better approach might be to provide only `MapView` but (optionally or always?) use an order-preserving encoding instead of BCS.

2023-12-16 20:29 UTC, MathieuDutSik commented
That PR is closed because it combines several unrelated issues.
Also, the issues of serialization are not well though out.

2023-12-16 20:29 UTC, closed without merging