Increase memory limit for queries in ScyllaDB
linera-io/linera-protocol pull request #1939
Opened 2024-04-23 14:03 UTC by christos-h

## Motivation

Memory quotas for queries are set implicitly via pagination. Even so the default limit of 1 Mb might be quite small .

## Proposal

Increase the memory limit to 100 Mb.

## Test Plan

CI will check any regressions. Otherwise this has been tested manually.

2024-04-23 14:17 UTC, andresilva91 approved these changes

2024-04-24 14:42 UTC, MathieuDutSik approved these changes
If that makes things work, I have no issue with this.

2024-04-24 15:38 UTC, christos-h commented
@ma2bd should I mark this as draft until we have more data?

2024-04-29 04:23 UTC, ma2bd requested changes
yes please

2024-05-01 02:54 UTC, ma2bd commented
closing for now

2024-05-01 02:54 UTC, closed without merging