Batch handling of certificates
linera-io/linera-protocol pull request #2040
Opened 2024-05-17 15:21 UTC by jvff

## Motivation

When synchronizing a chain, each certificate with a block is processed individually. This means that after each certificate is processed, the cross-chain requests handled, notifications are sent and the chain information is summarized. This is not optimal because these operations can be done once after all certificates have been processed.

## Proposal

Add a `ValidatorWorker::handle_certificates` that handles a batch of certificates. This allows performing once the execution all the cross-chain requests, sending notifications and summarizing the chain information.

## Test Plan

Tested manually, and it seems to h have improved the wallet initialization time from about 7 seconds to 6 seconds.

## Release Plan

This only changes the internal behavior of the client, so
- Need to bump the patch version number in the next release of the crates.

## Links

- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checklist)

2024-05-18 11:03 UTC, afck requested changes
~Since this isn't changing the updater I don't see how it actually uses `handle_certificates` anywhere?~

(Right, this is only used internally in the client's local node, not in requests the client sends to validators.)

2024-05-18 11:03 UTC, afck commented on linera-core/src/local_node.rs
> +            result = self.handle_certificates(certificates, &blobs).await;
This assumes that if one _or more_ of the certificates are missing bytecode, we get _only one_ `ApplicationBytecodesNotFound` error with _all_ the missing bytecode locations. I don't think that's currently the case?

2024-09-24 14:36 UTC, jvff commented
Moved to Testnet #2 because this requires a complete redesign of the solution.

2024-11-01 15:16 UTC, Twey commented
I'm a bit confused about the ‘Browser Wallet’ project on this PR.  What's the connection to the browser wallet?

2024-11-01 15:46 UTC, deuszx commented
> I'm a bit confused about the ‘Browser Wallet’ project on this PR. What's the connection to the browser wallet?

It might be worth reassessing whether these changes are still needed after recent work by @afck

2025-03-06 04:43 UTC, jvff commented
Closing because the solution needs to be restarted from scratch.

2025-03-06 04:43 UTC, closed without merging