Send Prometheus metrics to Grafana Cloud
linera-io/linera-protocol pull request #2994
Opened 2024-12-02 14:40 UTC by ndr-ds

## Motivation

We're migrating our internal validators to send data to Grafana Cloud.

## Proposal

Starting with the local setup. This was useful to test the required changes that we'll likely need for the actual internal validator setup. We probably won't want to send metrics to Grafana Cloud from local runs all the time (specially for cost reasons), so this is disabled by default.

Grafana Cloud credentials are stored in a secret within GCP's Secret Manager. Since Grafana Cloud will be for our internal validators, then I figured storing the secret on GCP made sense.

## Test Plan

Ran locally with `linera net up --kubernetes`, and saw the metrics in our Grafana Cloud instance:

![Screenshot 2024-12-02 at 11.37.04.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HlciHFAoHZW62zn13apJ/4b46c8bc-a5d3-4aad-9e3f-151cf44be947.png)

## Release Plan

If we want to start sending metrics to Grafana Cloud from our devnet/testnet, then:
- These changes should be backported to the latest `devnet` branch
- These changes should be backported to the latest `testnet` branch, then

2024-12-02 14:40 UTC, ndr-ds commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/2994?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2994** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/2994?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/2994?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#2986** <a href="https://app.graphite.dev/github/pr/linera-io/linera-protocol/2986?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-03 17:34 UTC, christos-h requested changes
Thanks for the cleanup.

I'm a bit confused on two things:
1. Do we not still want the internal Grafana which is validator specific? In which case why is the dashboard disabled? If you don't want the dashboard why not remove Grafana entirely?
2. The reference to the GCP secret should not be hard-coded in `linera-protocol` but instead be parameterised and injected by the caller in `linera-infra` (probably `lineractl`).

2024-12-03 20:00 UTC, ndr-ds commented
1. The way I did it, either you do Grafana Cloud (`writeToGrafanaCloud` set to `true`), or you do the same existing setup we have right now. With Grafana Cloud, we don't need the Grafana pod, or the dashboards or any of that. So the idea is that for internal validators we run it with `writeToGrafanaCloud` set to `true`, and for external validators we run it with `writeToGrafanaCloud` set to `false`.
2. Ok, sure, I can do that. I thought it was fine since you need to be authenticated with `gcloud` for the secret to be successfully fetched 🤔

2025-01-10 15:33 UTC, christos-h requested changes
Left some comments. Also the Kubernetes workflow is not passing. Although this may be unrelated to these changes.

2025-01-10 15:33 UTC, christos-h commented on kubernetes/linera-validator/templates/grafana-cloud-auth-secret.yaml
> +  username: {{ .Values.grafanaCloudUsername | quote }}
What happens if this isn't specified (for example external validators which use Kuberentes?).

2025-01-10 15:33 UTC, christos-h commented on kubernetes/linera-validator/values-local.yaml.gotmpl
> +lineraImage: {{ env "LINERA_HELMFILE_LINERA_IMAGE" | default "linera:latest" }}
Thanks for this. I'm not entirely sure if this is better or worse to be honest. On the one hand there is less indirection on the other hand configurable variables are now in more places.

2025-01-10 16:12 UTC, ndr-ds commented on kubernetes/linera-validator/templates/grafana-cloud-auth-secret.yaml
> +  username: {{ .Values.grafanaCloudUsername | quote }}
I'm currently changing this to only be created if `writeToGrafanaCloud` is `true`, which will only happen for internal validators

2025-01-10 16:12 UTC, ndr-ds commented on kubernetes/linera-validator/values-local.yaml.gotmpl
> +lineraImage: {{ env "LINERA_HELMFILE_LINERA_IMAGE" | default "linera:latest" }}
I think it definitely looks better/less confusing than just an empty string, tbh 🤔 at least now you know what the default for this is supposed to be

2025-01-10 16:12 UTC, ndr-ds commented
It's related, actually. Working on a fix right now!

2025-01-14 19:12 UTC, christos-h approved these changes

2025-01-29 10:43 UTC, ndr-ds commented
### Merge activity

* **Jan 29, 5:43 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/linera-io/linera-protocol/2994).

2025-01-29 10:43 UTC, merged