delete use KeyValueStore
linera-io/linera-protocol pull request #824
Opened 2023-06-10 05:13 UTC by firedpeanut

optimize code

2023-06-13 06:31 UTC, ma2bd commented on linera-sdk/src/views/mod.rs
> -pub use self::system_api::{KeyValueStore, ViewStorageContext};
I'm supportive but you also need to fix the docs.

2023-06-13 07:43 UTC, firedpeanut commented
is this ok?

2023-06-16 08:53 UTC, ma2bd requested changes
back to your queue

2023-06-16 09:36 UTC, firedpeanut commented on linera-sdk/src/views/system_api.rs
> +/// Implementation of [`linera_views::common::Context`] that uses the KeyValueStore to
OK

2023-06-16 11:08 UTC, ma2bd approved these changes

2023-06-16 11:08 UTC, merged